'use client'

import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowRight, Clock3, MessageCircle, Plus, Search, UsersRound } from 'lucide-react'
import StudentReferenceShell from '@/components/layout/StudentReferenceShell'
import { createPost, getForumCategories, getRecentPosts } from '@/lib/forumService'

const palette = ['blue', 'violet', 'rose', 'emerald', 'amber']
const initials = (name?: string) => name?.split(' ').map((word: string) => word[0]).join('').slice(0, 2).toUpperCase() || 'ST'
const ago = (value?: string) => { if (!value) return ''; const hours = Math.floor((Date.now() - new Date(value).getTime()) / 3600000); return hours < 1 ? 'just now' : hours < 24 ? `${hours}h ago` : `${Math.floor(hours / 24)}d ago` }

export default function ForumsPage() {
  const router = useRouter(), [categories, setCategories] = useState<any[]>([]), [posts, setPosts] = useState<any[]>([]), [search, setSearch] = useState(''), [tab, setTab] = useState('browse'), [creating, setCreating] = useState(false)
  const [form, setForm] = useState({ title: '', content: '', category: 'General Discussion' })
  useEffect(() => { Promise.all([getForumCategories(), getRecentPosts()]).then(([cats, recent]) => { setCategories(Array.isArray(cats) ? cats : []); setPosts(Array.isArray(recent) ? recent : []) }) }, [])
  const visiblePosts = useMemo(() => posts.filter(post => `${post.title} ${post.content} ${post.category}`.toLowerCase().includes(search.toLowerCase())), [posts, search])
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!form.title || !form.content) return; setCreating(true); try { const post = await createPost({ ...form, tags: [] }); if (post?.id) router.push(`/dashboard/student/forums/${post.id}`) } finally { setCreating(false) } }
  const shownCategories = categories.slice(0, 5)
  return <div className="forum-reference-page min-h-screen bg-[#f8faff]"><StudentReferenceShell active="discussions" /><main id="student-main" tabIndex={-1} className="forum-reference-main">
    <section className="forum-reference-hero"><img src="/images/community-forum-hero.png" alt="Students connecting on campus" /><div className="forum-reference-overlay" /><div className="forum-reference-title"><p>Home <span>/</span> Community <span>/</span> <b>Discussions</b></p><h1>Community Forums</h1><h2>Connect, discuss, and grow with your peers 🌎</h2><div className="forum-hero-stats"><Stat value="1.2K" label="Students" icon="👥" /><Stat value={String(posts.length)} label="Discussions" icon="💬" /><Stat value={String(Math.min(posts.length, 12))} label="Active Today" icon="♟" /></div></div><div className="forum-hero-words">SHARE<br />SUPPORT<br />LEARN<br />GROW</div></section>
    <section className="forum-reference-content"><div className="forum-toolbar"><div><Search /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search discussions, tags, or users..." /></div><button onClick={() => setTab('create')}><Plus /> New Post</button></div><div className="forum-tabs">{[['browse','▣ Browse'],['recent','◷ Recent'],['trending','♨ Trending'],['mine','♟ My Posts']].map(([id,label]) => <button key={id} onClick={() => setTab(id)} className={tab === id ? 'active' : ''}>{label}</button>)}</div>
      {tab === 'create' ? <form className="forum-create" onSubmit={submit}><h2>Start a discussion</h2><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{(categories.length ? categories : [{ name: 'General Discussion' }]).map(c => <option key={c.name} value={c.name}>{c.name}</option>)}</select><input placeholder="What would you like to discuss?" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /><textarea placeholder="Share details with the community..." value={form.content} onChange={e => setForm({ ...form, content: e.target.value })} /><button disabled={creating}>{creating ? 'Publishing...' : 'Publish Post'}</button></form> : <><div className="forum-category-row">{shownCategories.map((category, index) => <button key={category.id || category.name} className={`forum-category ${palette[index]}`} onClick={() => setSearch(category.name)}><span>{['💬','▣','🧠','▣','▣'][index]}</span><strong>{category.name}</strong><small><UsersRound /> {category.postsCount || 0} posts</small><ArrowRight /></button>)}</div><div className="forum-columns"><section className="forum-posts"><h2><MessageCircle /> Recent Discussions</h2>{visiblePosts.length ? visiblePosts.slice(0, 8).map(post => <button key={post.id} onClick={() => router.push(`/dashboard/student/forums/${post.id}`)} className="forum-post"><span className="forum-avatar">{initials(post.author?.name)}</span><div><strong>{post.title}</strong><p>{post.content}</p><small>{post.category || 'Discussion'} · {ago(post.createdAt)}</small></div><aside><MessageCircle /> {post.repliesCount || post.commentsCount || 0}</aside></button>) : <div className="forum-empty">No discussions have been posted yet. Be the first to start one.</div>}</section><aside className="forum-side"><section><h3>Community Stats</h3><div className="forum-stat-grid"><Stat value="1.2K" label="Total Members" icon="👥" /><Stat value={String(posts.length)} label="Total Discussions" icon="💬" /><Stat value={String(Math.min(posts.length,12))} label="Active Today" icon="●" /><Stat value={String(categories.length)} label="Categories" icon="▣" /></div></section><section><h3>Top Contributors</h3>{posts.slice(0,5).map((post,index) => <div className="contributor" key={post.id}><b>{index + 1}</b><span>{initials(post.author?.name)}</span><p>{post.author?.name || 'Community Member'}<small>{post.repliesCount || 0} posts</small></p></div>)}</section><section className="forum-help"><b>💡 Have a question?</b><p>Our community is here to help.</p><button onClick={() => setTab('create')}>Create Post <ArrowRight /></button></section></aside></div></>}</section>
  </main></div>
}
function Stat({ value, label, icon }: any) { return <div className="forum-stat"><span>{icon}</span><p><b>{value}</b><small>{label}</small></p></div> }
